// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgTuerjO40C8NKVz1aJm7CruwCueJjw84',
    appId: '1:600222600522:web:e9dca4efce22cbfe6205b3',
    messagingSenderId: '600222600522',
    projectId: 'klip-56f41',
    authDomain: 'klip-56f41.firebaseapp.com',
    storageBucket: 'klip-56f41.appspot.com',
    measurementId: 'G-KNEBE8WEP9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-9wbx-Km_9f_JH2EsFuZaMn84fWVuqjY',
    appId: '1:600222600522:android:9fe1a38d5b27d6046205b3',
    messagingSenderId: '600222600522',
    projectId: 'klip-56f41',
    storageBucket: 'klip-56f41.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADqLkT-XqgWbVwPJZHtTv9IYjWCsUwaM8',
    appId: '1:600222600522:ios:7b8e1e5745c4748f6205b3',
    messagingSenderId: '600222600522',
    projectId: 'klip-56f41',
    storageBucket: 'klip-56f41.appspot.com',
    iosClientId: '600222600522-hgreq902psndqlbe8pmk7fe6cvr7cdc3.apps.googleusercontent.com',
    iosBundleId: 'com.example.tubesKlip',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADqLkT-XqgWbVwPJZHtTv9IYjWCsUwaM8',
    appId: '1:600222600522:ios:7b8e1e5745c4748f6205b3',
    messagingSenderId: '600222600522',
    projectId: 'klip-56f41',
    storageBucket: 'klip-56f41.appspot.com',
    iosClientId: '600222600522-hgreq902psndqlbe8pmk7fe6cvr7cdc3.apps.googleusercontent.com',
    iosBundleId: 'com.example.tubesKlip',
  );
}
